import { today } from '../../lib/format'
export const configs = {
  categories: {
    endpoint: 'categories',
    title: 'A place for every product.',
    description:
      'Create and manage your product categories. Rename a category without losing its products.',
    singular: 'category',
    editable: true,
    fields: [{ key: 'name', label: 'Category name', required: true }],
    columns: [['name', 'Category']],
  },
  products: {
    endpoint: 'products',
    title: 'Good products. Great possibilities.',
    description: 'Your catalog, organized and ready for the next order.',
    singular: 'product',
    editable: true,
    fields: [
      { key: 'name', label: 'Product name', required: true },
      { key: 'sku', label: 'SKU', required: true },
      { key: 'category_id', label: 'Category', type: 'category', required: true },
      {
        key: 'selling_price',
        label: 'Selling price (PKR)',
        type: 'number',
        min: 0.01,
        required: true,
      },
      { key: 'low_stock_threshold', label: 'Low stock alert at', type: 'number', initial: 10 },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image_url', label: 'Product image', type: 'image' },
      { key: 'is_active', label: 'Product is active', type: 'checkbox', initial: 1 },
    ],
    columns: [
      ['name', 'Product'],
      ['sku', 'SKU'],
      ['selling_price', 'Selling price', 'money'],
      ['available', 'Available'],
      ['reserved', 'Reserved'],
      ['is_active', 'Status', 'active'],
    ],
  },
  inventory: {
    endpoint: 'stock-batches',
    title: 'Stock you can count on.',
    description: 'Track purchase batches, landed costs, and FIFO stock reservations.',
    singular: 'stock receipt',
    fields: [
      { key: 'product', label: 'Product', type: 'product', required: true },
      { key: 'reference', label: 'Purchase reference', required: true },
      {
        key: 'purchased_quantity',
        label: 'Quantity received',
        type: 'number',
        min: 1,
        required: true,
      },
      {
        key: 'purchase_amount',
        label: 'Purchase cost per unit (PKR)',
        type: 'number',
        min: 0,
        required: true,
      },
      {
        key: 'transport_cost',
        label: 'Total transport cost (PKR)',
        type: 'number',
        initial: 0,
        hint: 'Spread equally across all received units.',
      },
      {
        key: 'import_cost',
        label: 'Total import / customs cost (PKR)',
        type: 'number',
        initial: 0,
      },
      {
        key: 'received_at',
        label: 'Date received',
        type: 'date',
        initial: today(),
        required: true,
      },
    ],
    columns: [
      ['reference', 'Batch reference'],
      ['product_name', 'Product'],
      ['received_at', 'Received', 'date'],
      ['unit_cost', 'Landed unit cost', 'money'],
      ['remaining_quantity', 'On hand'],
      ['reserved_quantity', 'Reserved'],
    ],
  },
  packaging: {
    endpoint: 'packaging',
    title: 'The finishing touches.',
    description: 'Every flyer, box, and meter of wrap. Every cost accounted for.',
    singular: 'packaging item',
    editable: true,
    fields: [
      { key: 'name', label: 'Item name', required: true },
      {
        key: 'unit',
        label: 'Measurement unit',
        type: 'select',
        options: ['piece', 'meter', 'gram'],
        initial: 'piece',
      },
      { key: 'unit_cost', label: 'Cost per unit (PKR)', type: 'number', required: true },
      { key: 'stock', label: 'Stock on hand', type: 'number', required: true },
      {
        key: 'default_quantity',
        label: 'Suggested quantity per order',
        type: 'number',
        initial: 1,
      },
    ],
    columns: [
      ['name', 'Packaging item'],
      ['unit', 'Unit'],
      ['unit_cost', 'Unit cost', 'money'],
      ['stock', 'On hand'],
      ['default_quantity', 'Suggested per order'],
    ],
  },
  couriers: {
    endpoint: 'couriers',
    title: 'Better deliveries start here.',
    description: 'Your courier contracts, weight rates, and return charges in one place.',
    singular: 'courier contract',
    editable: true,
    fields: [
      {
        key: 'provider',
        label: 'Shipping service',
        type: 'select',
        options: [
          'TCS',
          'Leopards',
          'M&P',
          'Trax',
          'Daewoo',
          'Dastaq Logistic',
          'AHL',
          'PostEx',
          'Others',
        ],
        initial: 'TCS',
        required: true,
      },
      {
        key: 'name',
        label: 'Contract name',
        required: true,
        hint: 'Example: TCS standard COD, or the name of your other shipping service.',
      },
      {
        key: 'code',
        label: 'Unique courier code',
        required: true,
        hint: 'Lowercase letters, numbers, and hyphens.',
      },
      { key: 'base_weight', label: 'Base weight (kg)', type: 'number', min: 0.01, initial: 0.5 },
      { key: 'base_rate', label: 'Base rate (PKR)', type: 'number', required: true },
      { key: 'additional_kg_rate', label: 'Each additional kg (PKR)', type: 'number', initial: 0 },
      { key: 'tax_percent', label: 'Tax on shipping (%)', type: 'number', initial: 0 },
      { key: 'fixed_charge', label: 'Other fixed charge (PKR)', type: 'number', initial: 0 },
      { key: 'return_rate', label: 'Return charge (PKR)', type: 'number', initial: 0 },
      { key: 'is_active', label: 'Contract is active', type: 'checkbox', initial: 1 },
    ],
    columns: [
      ['name', 'Courier'],
      ['provider', 'Shipping service'],
      ['base_rate', 'Base rate', 'money'],
      ['base_weight', 'Base weight (kg)'],
      ['tax_percent', 'Tax %'],
      ['return_rate', 'Return fee', 'money'],
      ['is_active', 'Status', 'active'],
    ],
  },
  customers: {
    endpoint: 'customers',
    title: 'People, not just orders.',
    description: 'Get to know your customers and their delivery history.',
    singular: 'customer',
    editable: true,
    fields: [
      { key: 'name', label: 'Full name', required: true },
      { key: 'phone', label: 'Phone number', type: 'tel', required: true },
      { key: 'email', label: 'Email address', type: 'email' },
      { key: 'city', label: 'City', required: true },
      { key: 'province', label: 'Province / territory' },
      { key: 'address', label: 'Delivery address', type: 'textarea', required: true },
      { key: 'notes', label: 'Internal notes', type: 'textarea' },
    ],
    columns: [
      ['name', 'Customer'],
      ['phone', 'Phone'],
      ['city', 'City'],
      ['order_count', 'Orders'],
      ['returned_count', 'Returns'],
      ['email', 'Email'],
    ],
  },
  marketing: {
    endpoint: 'campaigns',
    title: 'Make every ad rupee matter.',
    description: 'Allocate campaign spend to orders, and see the real cost of growth.',
    singular: 'campaign',
    fields: [
      { key: 'name', label: 'Campaign name', required: true },
      {
        key: 'channel',
        label: 'Channel',
        type: 'select',
        options: ['Meta', 'Google', 'TikTok', 'Other'],
        initial: 'Meta',
      },
      { key: 'spend', label: 'Total spend (PKR)', type: 'number', min: 0.01, required: true },
      { key: 'start_date', label: 'Start date', type: 'date', initial: today(), required: true },
      { key: 'end_date', label: 'End date', type: 'date', initial: today(), required: true },
    ],
    columns: [
      ['name', 'Campaign'],
      ['channel', 'Channel'],
      ['spend', 'Ad spend', 'money'],
      ['start_date', 'From', 'date'],
      ['end_date', 'To', 'date'],
      ['allocation_count', 'Allocated orders'],
      ['allocated', 'Status', 'allocation'],
    ],
  },
  expenses: {
    endpoint: 'expenses',
    title: 'Keep the whole picture in view.',
    description: 'Rent, salaries, software, and all the costs beyond an order.',
    singular: 'expense',
    fields: [
      { key: 'name', label: 'Expense name', required: true },
      {
        key: 'category',
        label: 'Category',
        type: 'select',
        options: ['rent', 'salary', 'software', 'utilities', 'other'],
        initial: 'other',
      },
      { key: 'amount', label: 'Amount (PKR)', type: 'number', min: 0.01, required: true },
      { key: 'date', label: 'Expense date', type: 'date', initial: today(), required: true },
      { key: 'notes', label: 'Notes / reference', type: 'textarea' },
    ],
    columns: [
      ['name', 'Expense'],
      ['category', 'Category'],
      ['date', 'Date', 'date'],
      ['amount', 'Amount', 'money'],
      ['notes', 'Notes'],
      ['bank_paid', 'Bank payment recorded', 'money'],
      ['bank_remaining', 'Left to record', 'money'],
    ],
  },
}
